/*
CP 1 - ENTREGA DIA 23/03
LUIS HENRIQUE RM552692
SABRINA CAFÉ RM553568
MATHEUS DUARTE RM554199
*/

CREATE TABLE tabela_de_pedidos AS 
SELECT * FROM PF1788.PEDIDO;

SELECT COUNT(*) FROM tabela_de_pedidos;--QUANTOS RESULTADOS APARECERAM

--CONFERINDO OS RESULTADOS NA TABELA DO PROFESSOR...
SELECT * FROM tabela_de_pedidos FETCH FIRST 10 ROWS ONLY; 

DESC tabela_de_pedidos;


/**************************************************************************/

SET SERVEROUTPUT ON;


-- EX1: Desenvolvimento do Modelo Estrela
  
--CRIANDO TABELAS DE DIMENSÃO


--CLIENTE
CREATE TABLE DIM_CLIENTE (
    COD_CLIENTE NUMBER(10,0) NOT NULL ENABLE,
    NOME_CLIENTE VARCHAR2(100 BYTE),
    PERFIL_CONSUMO VARCHAR2(50 BYTE),
    CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

--VENDEDOR
CREATE TABLE DIM_VENDEDOR (
    COD_VENDEDOR NUMBER(4,0) NOT NULL ENABLE,
    NOME_VENDEDOR VARCHAR2(100 BYTE),
    CONSTRAINT PK_DIM_VENDEDOR PRIMARY KEY (COD_VENDEDOR)
);

--PRODUTO
CREATE TABLE DIM_PRODUTO (
    COD_PRODUTO NUMBER(10,0) NOT NULL ENABLE,
    NOME_PRODUTO VARCHAR2(100 BYTE),
    CATEGORIA VARCHAR2(50 BYTE),
    CONSTRAINT PK_DIM_PRODUTO PRIMARY KEY (COD_PRODUTO)
);

--STATUS
CREATE TABLE DIM_STATUS (
    COD_STATUS NUMBER(5,0) NOT NULL ENABLE,
    DESCRICAO_STATUS VARCHAR2(20 BYTE),
    CONSTRAINT PK_DIM_STATUS PRIMARY KEY (COD_STATUS)
);

--PAGAMENTO
CREATE TABLE DIM_PAGAMENTO (
    COD_PAGAMENTO NUMBER(5,0) NOT NULL ENABLE,
    FORMA_PAGAMENTO VARCHAR2(30 BYTE),
    PARCELADO VARCHAR2(3 BYTE), -- Sim/Não
    CONSTRAINT PK_DIM_PAGAMENTO PRIMARY KEY (COD_PAGAMENTO)
);


--CRIAÇÃO DA TABELA FATO_VENDA
CREATE TABLE FATO_VENDAS (
    ID_VENDA NUMBER(12,0) NOT NULL ENABLE,  
    COD_CLIENTE NUMBER(10,0),
    COD_VENDEDOR NUMBER(4,0),
    COD_STATUS NUMBER(5,0),
    COD_PAGAMENTO NUMBER(5,0),
    COD_PRODUTO NUMBER(10,0),  
    QTD_PRODUTO_VENDIDO NUMBER(10,0),  
    VAL_TOTAL_PEDIDO NUMBER(12,2),
    VAL_DESCONTO NUMBER(12,2),
    CONSTRAINT PK_FATO_VENDAS PRIMARY KEY (ID_VENDA),
    CONSTRAINT FK_FATO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES DIM_CLIENTE (COD_CLIENTE) ENABLE,
    CONSTRAINT FK_FATO_VENDEDOR FOREIGN KEY (COD_VENDEDOR) REFERENCES DIM_VENDEDOR (COD_VENDEDOR) ENABLE,
    CONSTRAINT FK_FATO_STATUS FOREIGN KEY (COD_STATUS) REFERENCES DIM_STATUS (COD_STATUS) ENABLE,
    CONSTRAINT FK_FATO_PAGAMENTO FOREIGN KEY (COD_PAGAMENTO) REFERENCES DIM_PAGAMENTO (COD_PAGAMENTO) ENABLE,
    CONSTRAINT FK_FATO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES DIM_PRODUTO (COD_PRODUTO) ENABLE
);

SELECT * FROM DIM_CLIENTE;
SELECT * FROM DIM_VENDEDOR;
SELECT * FROM DIM_PRODUTO;
SELECT * FROM DIM_STATUS;
SELECT * FROM DIM_PAGAMENTO;
SELECT * FROM FATO_VENDAS;

--POPULANDO


























